/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import clases.DolarConversion;
import clases.EuroConversion;
import clases.LibrasConversion;
import clases.WonConversion;
import clases.YenConversion;
import javax.swing.JOptionPane;

/**
 *
 * @author Johan
 */
public class OpcionesMonedas extends javax.swing.JFrame {

    /**
     * Creates new form OpcionesMonedas
     */
    MenuPrincipal menuPrincipal;
    boolean isConversionToColombianCurrency = false;

    public OpcionesMonedas(MenuPrincipal menuPrincipal) {
        initComponents();
        this.setTitle("Conversor Divisas");
        this.menuPrincipal = menuPrincipal;
        this.menuPrincipal.setVisible(false);
        jcCombox.addItem("Seleccione una opción:");
        jcCombox.addItem("De pesos a dolar");
        jcCombox.addItem("De pesos a euros");
        jcCombox.addItem("De pesos a libras");
        jcCombox.addItem("De pesos a wones");
        jcCombox.addItem("De pesos a yenes");
        jcCombox.addItem("De dolar a pesos");
        jcCombox.addItem("De euros a pesos");
        jcCombox.addItem("De libras a pesos");
        jcCombox.addItem("De wones a pesos");
        jcCombox.addItem("De yenes a pesos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcCombox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Elige la moneda a la cual deseas convertir tu dinero:");

        jcCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcComboxActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jcCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jcCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcComboxActionPerformed

    }//GEN-LAST:event_jcComboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        this.menuPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jcCombox.getSelectedIndex() == 1 || jcCombox.getSelectedIndex() == 6) {
            if (jcCombox.getSelectedIndex() == 6) {
                this.isConversionToColombianCurrency = true;
            }
            DolarConversion dolarConversion = new DolarConversion();
            VistaCantidadDinero vistaCantidadDinero = new VistaCantidadDinero(this, dolarConversion, this.isConversionToColombianCurrency);
            vistaCantidadDinero.setVisible(true);
        } else if (jcCombox.getSelectedIndex() == 2 || jcCombox.getSelectedIndex() == 7) {
            if (jcCombox.getSelectedIndex() == 7) {
                this.isConversionToColombianCurrency = true;
            }
            EuroConversion euroConversion = new EuroConversion();
            VistaCantidadDinero vistaCantidadDinero = new VistaCantidadDinero(this, euroConversion, this.isConversionToColombianCurrency);
            vistaCantidadDinero.setVisible(true);
        } else if (jcCombox.getSelectedIndex() == 3 || jcCombox.getSelectedIndex() == 8) {
            if (jcCombox.getSelectedIndex() == 8) {
                this.isConversionToColombianCurrency = true;
            }
            LibrasConversion librasConversion = new LibrasConversion();
            VistaCantidadDinero vistaCantidadDinero = new VistaCantidadDinero(this, librasConversion, this.isConversionToColombianCurrency);
            vistaCantidadDinero.setVisible(true);
        } else if (jcCombox.getSelectedIndex() == 4 || jcCombox.getSelectedIndex() == 9) {
            if (jcCombox.getSelectedIndex() == 9) {
                this.isConversionToColombianCurrency = true;
            }
            WonConversion wonConversion = new WonConversion();
            VistaCantidadDinero vistaCantidadDinero = new VistaCantidadDinero(this, wonConversion, this.isConversionToColombianCurrency);
            vistaCantidadDinero.setVisible(true);
        } else if (jcCombox.getSelectedIndex() == 5 || jcCombox.getSelectedIndex() == 10) {
            if (jcCombox.getSelectedIndex() == 10) {
                this.isConversionToColombianCurrency = true;
            }
            YenConversion yenConversion = new YenConversion();
            VistaCantidadDinero vistaCantidadDinero = new VistaCantidadDinero(this, yenConversion, this.isConversionToColombianCurrency);
            vistaCantidadDinero.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona una opción valida.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcCombox;
    // End of variables declaration//GEN-END:variables
}
